-- 1. Create hospitals table
CREATE TABLE IF NOT EXISTS public.hospitals (
  id text PRIMARY KEY,
  name text,
  city text,
  rating numeric,
  reviews integer,
  branches jsonb,
  departments jsonb,
  emergency boolean,
  facilities jsonb,
  phone text
);

-- 2. Enable Read Access (so the app can query it without logging in)
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users on hospitals" ON public.hospitals FOR SELECT USING (true);

-- 3. Insert Hospitals (Upsert to avoid duplicates)
INSERT INTO public.hospitals (id, name, city, rating, reviews, branches, departments, emergency, facilities, phone) VALUES
(
  'h1',
  'Lakeside General Hospital',
  'Colombo',
  4.7,
  1840,
  '["Colombo 07","Dehiwala","Kelaniya"]'::jsonb,
  '["Dermatology","Oral Medicine","General Medicine","Radiology"]'::jsonb,
  true,
  '["24/7 Emergency","Digital Imaging","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 234 5678'
),
(
  'h2',
  'Metro Cancer Institute',
  'Colombo',
  4.9,
  962,
  '["Nugegoda","Colombo 05"]'::jsonb,
  '["Oncology","Gynaecology","Pathology","Radiology"]'::jsonb,
  true,
  '["PET-CT","Biopsy Unit","Chemotherapy Suite","Counselling"]'::jsonb,
  '+94 11 765 4321'
),
(
  'h3',
  'Vision Care Hospital',
  'Kandy',
  4.6,
  512,
  '["Kandy","Matale"]'::jsonb,
  '["Ophthalmology","Optometry","General Medicine"]'::jsonb,
  false,
  '["OCT Scanning","Day Surgery","Optical Store"]'::jsonb,
  '+94 81 220 1122'
),
(
  'h4',
  'Riverstone Medical Centre',
  'Galle',
  4.5,
  738,
  '["Galle","Hikkaduwa"]'::jsonb,
  '["General Medicine","Cardiology","Dermatology"]'::jsonb,
  true,
  '["24/7 Emergency","Laboratory","Physiotherapy"]'::jsonb,
  '+94 91 224 3344'
),
(
  'h5-nawaloka',
  'Nawaloka Hospital',
  'Colombo',
  4.8,
  4210,
  '["Colombo 02","Negombo"]'::jsonb,
  '["Cardiology","Neurology","Ophthalmology","Orthopaedic Surgery","General Surgery","Oncology","Gynaecology","Subfertility","Oral & Maxillofacial Surgery","Psychiatry","Nephrology","General Medicine"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","NICU","Cath Lab","MRI","CT Scan","Digital X-Ray","Fertility Centre","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 254 4444'
),
(
  'h6-durdans',
  'Durdans Hospital',
  'Colombo',
  4.8,
  3850,
  '["Colombo 03","Galle"]'::jsonb,
  '["Cardiology","Neurology","Oncology","Nephrology","General Surgery","Ophthalmology","Rheumatology","General Medicine","Psychiatry"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","Cath Lab","MRI","CT Scan","PET-CT","Nuclear Medicine","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 541 0000'
),
(
  'h7-asiri-central',
  'Asiri Central Hospital',
  'Colombo',
  4.7,
  3200,
  '["Colombo 10"]'::jsonb,
  '["Cardiology","Neurology","Ophthalmology","Orthopaedic Surgery","General Surgery","Oncology","Psychiatry","General Medicine"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","MRI","CT Scan","Cath Lab","Endoscopy","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 466 5500'
),
(
  'h8-asiri-surgical',
  'Asiri Surgical Hospital',
  'Colombo',
  4.8,
  2890,
  '["Colombo 05"]'::jsonb,
  '["Cardiology","Neurology","General Surgery","Orthopaedic Surgery","Oncology","Ophthalmology","Nephrology"]'::jsonb,
  true,
  '["24/7 Emergency","Advanced Surgical Suites","ICU","MRI","CT Scan","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 452 4400'
),
(
  'h9-lanka',
  'Lanka Hospitals',
  'Colombo',
  4.7,
  3500,
  '["Colombo 05"]'::jsonb,
  '["Cardiology","Neurology","Oncology","Rheumatology","General Surgery","General Medicine","Ophthalmology","Orthopaedic Surgery","Nephrology","Psychiatry"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","NICU","Cath Lab","MRI","CT Scan","Robotic Surgery","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 553 0000'
),
(
  'h10-hemas-wattala',
  'Hemas Hospital Wattala',
  'Colombo',
  4.6,
  1420,
  '["Wattala"]'::jsonb,
  '["General Surgery","General Medicine","Gynaecology","Orthopaedic Surgery","Cardiology"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","CT Scan","Digital X-Ray","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 488 8888'
),
(
  'h11-hemas-thalawathugoda',
  'Hemas Hospital Thalawathugoda',
  'Colombo',
  4.6,
  1180,
  '["Thalawathugoda"]'::jsonb,
  '["General Surgery","General Medicine","Gynaecology","Rheumatology","Cardiology"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","CT Scan","Digital X-Ray","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 411 5000'
),
(
  'h12-kings',
  'Kings Hospital',
  'Colombo',
  4.5,
  1650,
  '["Colombo 08"]'::jsonb,
  '["General Surgery","Neurology","Ophthalmology","Nephrology","General Medicine","Psychiatry"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","CT Scan","MRI","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 501 5000'
),
(
  'h13-ninewells',
  'Ninewells Hospital',
  'Colombo',
  4.7,
  2100,
  '["Colombo 05"]'::jsonb,
  '["General Surgery","Cardiology","Neurology","General Medicine","Oral & Maxillofacial Surgery","Gynaecology","Fertility Centre"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","Fertility Centre","MRI","CT Scan","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 204 9999'
),
(
  'h14-royal',
  'Royal Hospital',
  'Colombo',
  4.6,
  1950,
  '["Colombo 07"]'::jsonb,
  '["General Surgery","Cardiology","Neurology","General Medicine","Psychiatry","Ophthalmology"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","CT Scan","MRI","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 255 0000'
),
(
  'h15-asiri-kandy',
  'Asiri Hospital Kandy',
  'Kandy',
  4.6,
  890,
  '["Kandy"]'::jsonb,
  '["General Medicine","Oncology","General Surgery","Cardiology","Neurology"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","CT Scan","MRI","Pharmacy","Laboratory"]'::jsonb,
  '+94 81 222 4400'
),
(
  'h16-neville-fernando',
  'Neville Fernando Teaching Hospital',
  'Colombo',
  4.5,
  780,
  '["Malabe"]'::jsonb,
  '["General Surgery","Nephrology","General Medicine","Cardiology","Orthopaedic Surgery"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","Teaching Facilities","CT Scan","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 247 5000'
),
(
  'h17-asiri-medical',
  'Asiri Medical Hospital',
  'Colombo',
  4.7,
  2650,
  '["Colombo 08"]'::jsonb,
  '["Neurology","Nephrology","Psychiatry","General Medicine","Rheumatology","Oncology"]'::jsonb,
  true,
  '["24/7 Emergency","ICU","MRI","CT Scan","PET-CT","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 452 7000'
),
(
  'h18-medihelp',
  'Medihelp Hospitals',
  'Colombo',
  4.4,
  1350,
  '["Colombo 10","Panadura","Horana","Avissawella"]'::jsonb,
  '["General Medicine","Cardiology","Neurology","Nephrology","General Surgery"]'::jsonb,
  true,
  '["24/7 Emergency","CT Scan","Digital X-Ray","Pharmacy","Laboratory"]'::jsonb,
  '+94 11 231 6666'
),
(
  'h19-ceymed',
  'Ceymed Healthcare Services',
  'Colombo',
  4.5,
  920,
  '["Colombo 02"]'::jsonb,
  '["General Medicine","Neurology","Oncology","Nephrology","General Surgery"]'::jsonb,
  false,
  '["Channelling Centre","Laboratory","Pharmacy","Digital X-Ray"]'::jsonb,
  '+94 11 230 0600'
)
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  rating = EXCLUDED.rating,
  reviews = EXCLUDED.reviews,
  branches = EXCLUDED.branches,
  departments = EXCLUDED.departments,
  emergency = EXCLUDED.emergency,
  facilities = EXCLUDED.facilities,
  phone = EXCLUDED.phone;

-- 4. Insert Doctors
-- Note: Assuming you run this in the Supabase SQL editor as an Admin (postgres role), 
-- this will bypass any RLS policies that block anonymous inserts.
INSERT INTO public.doctors_roster (id, name, specialty, hospital, branch, city, "distanceKm", "experienceYears", rating, reviews, fee, languages, online, queue, "nextSlot", "photoInitials", about) VALUES
(
  'd1',
  'Dr. Amara Silva',
  'Dermatology',
  'Lakeside General Hospital',
  'Colombo 07',
  'Colombo',
  2.4,
  14,
  4.9,
  412,
  4500,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Today · 16:30',
  'AS',
  'Consultant dermatologist focused on early detection of skin lesions and pigmented mole assessment.'
),
(
  'd1-b',
  'Dr. Amara Silva',
  'Dermatology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  14,
  4.9,
  412,
  5000,
  '["English","Sinhala"]'::jsonb,
  true,
  1,
  'Tomorrow · 10:00',
  'AS',
  'Consultant dermatologist focused on early detection of skin lesions and pigmented mole assessment.'
),
(
  'd2',
  'Dr. Nuwan Perera',
  'Oncology',
  'Metro Cancer Institute',
  'Nugegoda',
  'Colombo',
  6.1,
  21,
  4.8,
  289,
  7500,
  '["English","Sinhala","Tamil"]'::jsonb,
  false,
  8,
  'Tomorrow · 09:00',
  'NP',
  'Medical oncologist specialising in breast and oral cancer screening pathways.'
),
(
  'd3',
  'Dr. Hasini Fernando',
  'Ophthalmology',
  'Vision Care Hospital',
  'Kandy',
  'Kandy',
  12.8,
  9,
  4.7,
  168,
  3500,
  '["English","Sinhala"]'::jsonb,
  true,
  1,
  'Today · 18:00',
  'HF',
  'Eye surgeon treating anterior segment infections and diabetic retinal screening.'
),
(
  'd4',
  'Dr. Ravi Kumar',
  'Dentistry & Oral Medicine',
  'Lakeside General Hospital',
  'Dehiwala',
  'Colombo',
  4.9,
  17,
  4.6,
  233,
  3000,
  '["English","Tamil"]'::jsonb,
  false,
  5,
  'Fri · 11:15',
  'RK',
  'Oral medicine specialist with an interest in persistent ulcers and mucosal lesions.'
),
(
  'd5',
  'Dr. Ishara Jayawardena',
  'General Medicine',
  'Riverstone Medical Centre',
  'Galle',
  'Galle',
  3.2,
  11,
  4.8,
  351,
  2500,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Today · 15:00',
  'IJ',
  'Primary care physician coordinating referrals and preventive health reviews.'
),
(
  'd6',
  'Dr. Menaka De Alwis',
  'Gynaecology',
  'Metro Cancer Institute',
  'Colombo 05',
  'Colombo',
  5.5,
  16,
  4.9,
  402,
  5500,
  '["English","Sinhala"]'::jsonb,
  true,
  4,
  'Tomorrow · 10:30',
  'MD',
  'Consultant gynaecologist leading the breast and cervical screening clinic.'
),
(
  'd7-psych',
  'Dr. Anura Senanayake',
  'Psychiatry & Mental Health',
  'Lakeside General Hospital',
  'Colombo 07',
  'Colombo',
  2.1,
  18,
  4.9,
  489,
  4500,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Today · 17:00',
  'AS',
  'Consultant Psychiatrist specializing in anxiety disorders, clinical depression, CBT therapy, and stress management.'
),
(
  'd8-psych',
  'Dr. Diluka Wickramasinghe',
  'Psychiatry & Mental Health',
  'Metro Mind Wellness Institute',
  'Colombo 05',
  'Colombo',
  3.8,
  14,
  4.8,
  310,
  4000,
  '["English","Sinhala"]'::jsonb,
  true,
  1,
  'Tomorrow · 10:00',
  'DW',
  'Senior Consultant Psychiatrist & Behavioral Therapist focusing on holistic mental wellness and adult psychiatry.'
),
(
  'd9-uj',
  'Dr. Udara Jayawardena',
  'Subfertility & Gynaecology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  15,
  4.9,
  387,
  5500,
  '["English","Sinhala"]'::jsonb,
  true,
  4,
  'Tomorrow · 09:30',
  'UJ',
  'Consultant in Subfertility & Gynaecology specialising in IVF, IUI, obstetrics & gynaecology services across multiple fertility centres.'
),
(
  'd10-kb',
  'Dr. Kapila Banduthilaka',
  'Ophthalmology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  22,
  4.8,
  276,
  4500,
  '["English","Sinhala"]'::jsonb,
  false,
  6,
  'Today · 17:00',
  'KB',
  'MBBS, MD, FRCS — Eye Surgeon specialising in cataract surgery, glaucoma management and retinal conditions.'
),
(
  'd11-jm',
  'Dr. Jayan Mendis',
  'Psychiatry & Mental Health',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  20,
  4.9,
  452,
  5000,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Today · 16:00',
  'JM',
  'MBBS, MD(Psych), FSLC Psych, FCCP — Senior Consultant Psychiatrist practising across multiple leading hospitals.'
),
(
  'd12-cp',
  'Dr. C. Prasanna',
  'Oral & Maxillofacial Surgery',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  16,
  4.7,
  198,
  5000,
  '["English","Sinhala"]'::jsonb,
  false,
  5,
  'Fri · 10:00',
  'CP',
  'MD-OMFS(Col), BDS(SL), MFDSRCPS(UK) — Oral & Maxillofacial Surgeon treating complex jaw, facial and oral conditions.'
),
(
  'd13-ej',
  'Dr. Eshan Jayaweera',
  'Orthopaedic Surgery',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  12,
  4.8,
  311,
  5500,
  '["English","Sinhala"]'::jsonb,
  false,
  7,
  'Tomorrow · 11:00',
  'EJ',
  'MBBS, D. Sports Medicine, MRCS(UK), MD Orthopaedic Surgery — Orthopaedic Surgeon specialising in sports injuries and joint reconstruction.'
),
(
  'd14-tt',
  'Dr. T. Thivakaran',
  'Neurology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  25,
  4.9,
  523,
  6000,
  '["English","Sinhala","Tamil"]'::jsonb,
  true,
  4,
  'Today · 15:30',
  'TT',
  'MBBS, MD, MRCP Neurology (UK), FRCP London, FCCP — Senior Consultant Neurologist treating stroke, epilepsy and neurodegenerative conditions.'
),
(
  'd15-mr',
  'Dr. M.B.F. Rahuman',
  'Cardiology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  19,
  4.8,
  398,
  6000,
  '["English","Sinhala","Tamil"]'::jsonb,
  true,
  5,
  'Tomorrow · 10:00',
  'MR',
  'Consultant Cardiologist providing cardiology & ECHO services across major hospitals in Colombo.'
),
(
  'd16-pp',
  'Dr. Prasad Pathirana',
  'Ophthalmology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  23,
  4.9,
  467,
  5000,
  '["English","Sinhala"]'::jsonb,
  false,
  3,
  'Today · 18:00',
  'PP',
  'MBBS Colombo, MD Sri Lanka, FRCS-OPHTH(UK) — Senior Eye Surgeon specialising in advanced ophthalmic surgery and retinal treatments.'
),
(
  'd17-hp',
  'Dr. Harshani Perera',
  'Nephrology',
  'Durdans Hospital',
  'Colombo 03',
  'Colombo',
  3.5,
  14,
  4.7,
  215,
  5000,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Tomorrow · 14:00',
  'HP',
  'Consultant Nephrologist managing chronic kidney disease, dialysis care and renal transplant follow-up.'
),
(
  'd18-kg',
  'Dr. Kishara Gooneratne',
  'Neurology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  3.5,
  16,
  4.8,
  342,
  5500,
  '["English","Sinhala"]'::jsonb,
  true,
  4,
  'Today · 16:30',
  'KG',
  'MBBS(Col), MD(Col), MRCP(UK) — Consultant Neurologist practising at Durdans, Asiri and multiple leading hospitals.'
),
(
  'd19-ha',
  'Dr. Himantha Atukorale',
  'Rheumatology',
  'Lanka Hospitals',
  'Colombo 05',
  'Colombo',
  5.2,
  18,
  4.8,
  287,
  5000,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Tomorrow · 09:00',
  'HA',
  'MBBS, MD-Medicine, FRCP, FACR — Consultant Rheumatologist treating autoimmune disorders, arthritis and connective tissue diseases.'
),
(
  'd20-gr',
  'Dr. Gotabhaya Ranasinghe',
  'Cardiology',
  'Asiri Surgical Hospital',
  'Colombo 05',
  'Colombo',
  5.5,
  28,
  4.9,
  612,
  7000,
  '["English","Sinhala"]'::jsonb,
  false,
  8,
  'Wed · 09:00',
  'GR',
  'MBBS(Hons), MD, MRCP, FRCP, FCCP, FAPSIC, FACC, FESC — Senior Consultant Cardiologist with advanced interventional cardiology expertise.'
),
(
  'd21-aa',
  'Dr. Anurudda Ariyawansha',
  'General Medicine',
  'Asiri Hospital Kandy',
  'Kandy',
  'Kandy',
  115,
  13,
  4.7,
  189,
  3500,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Tomorrow · 10:30',
  'AA',
  'MBBS [Kelaniya], MD-Medicine [Colombo], MRCP [UK] — Consultant Physician providing comprehensive medical care in the Kandy region.'
),
(
  'd22-sn',
  'Dr. S. Naveenakumar',
  'General Medicine',
  'Lanka Hospitals',
  'Colombo 05',
  'Colombo',
  5.2,
  15,
  4.6,
  234,
  3000,
  '["English","Sinhala","Tamil"]'::jsonb,
  true,
  3,
  'Today · 14:00',
  'SN',
  'General Physician offering comprehensive primary care and chronic disease management across multiple Colombo hospitals.'
),
(
  'd23-kr',
  'Dr. Keerthi Rajapaksha',
  'General Surgery',
  'Hemas Hospital Wattala',
  'Wattala',
  'Colombo',
  11.3,
  20,
  4.8,
  356,
  5000,
  '["English","Sinhala"]'::jsonb,
  false,
  6,
  'Thu · 09:00',
  'KR',
  'Consultant Surgeon providing general surgical services including laparoscopic surgery across Hemas, Kings, and Lanka hospital networks.'
),
(
  'd24-bt',
  'Dr. Bhishman Thevarajah',
  'General Surgery',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  22,
  4.9,
  478,
  5500,
  '["English","Sinhala","Tamil"]'::jsonb,
  false,
  7,
  'Tomorrow · 08:30',
  'BT',
  'Senior Consultant Surgeon practising at Nawaloka, Durdans, Asiri, Kings, Lanka, Ninewells, Royal and other leading hospitals.'
),
(
  'd25-vr',
  'Dr. V.T. Rajendiran',
  'Neurology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  17,
  4.7,
  298,
  5500,
  '["English","Sinhala","Tamil"]'::jsonb,
  true,
  4,
  'Today · 17:30',
  'VR',
  'Consultant Neurologist providing neurological care at Nawaloka, Durdans, Lanka, Royal and multiple channelling centres.'
),
(
  'd26-rg',
  'Dr. Roshan Gunarathna',
  'Oncology',
  'Durdans Hospital',
  'Colombo 03',
  'Colombo',
  3.5,
  19,
  4.8,
  345,
  6500,
  '["English","Sinhala"]'::jsonb,
  true,
  5,
  'Wed · 10:00',
  'RG',
  'Consultant Clinical Oncologist providing cancer treatment services at Durdans, Asiri, Lanka and other hospitals across Sri Lanka.'
),
(
  'd27-spd',
  'Dr. S.P. Dissanayake',
  'Rheumatology',
  'Durdans Medical Centre Galle',
  'Galle',
  'Galle',
  120,
  16,
  4.7,
  167,
  4000,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Tomorrow · 11:00',
  'SD',
  'Consultant Rheumatologist serving Galle region hospitals including Asiri Galle, Durdans Medical Centre and Queensbury.'
),
(
  'd28-pj',
  'Dr. Priyankara Jayawardena',
  'General Medicine',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  24,
  4.9,
  512,
  4500,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Today · 16:00',
  'PJ',
  'MBBS, MD, MRCP, FRCP, FACP, FCCP, Dip in Geriatric Medicine — Consultant Physician'
),
(
  'd29-bs',
  'Dr. Bimsara Senanayake',
  'Neurology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  20,
  4.8,
  402,
  5500,
  '["English","Sinhala"]'::jsonb,
  true,
  4,
  'Tomorrow · 10:00',
  'BS',
  'MBBS (Col), MD (Colombo), FRCP (London), FCCP — Neuro Physician'
),
(
  'd30-nh',
  'Dr. Nalinda Herath',
  'Nutrition',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  12,
  4.6,
  156,
  3500,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Tomorrow · 14:00',
  'NH',
  'Nutrition Physician specialising in dietary management and metabolic health.'
),
(
  'd31-kr',
  'Dr. Kapila Ranasinghe',
  'Psychiatry & Mental Health',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  18,
  4.7,
  320,
  4000,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Today · 18:30',
  'KR',
  'MBBS, MD (Psychiatry), FSLPSYCH — Consultant Psychiatrist'
),
(
  'd32-jr',
  'Dr. J. C. P. Rajendra',
  'General Medicine',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  22,
  4.8,
  410,
  3500,
  '["English","Tamil","Sinhala"]'::jsonb,
  true,
  4,
  'Tomorrow · 09:30',
  'JR',
  'MBBS, MD (Medicine) (Col), FCGP — General Physician'
),
(
  'd33-nj',
  'Dr. N. D. Jayaweerabandara',
  'General Medicine',
  'Lanka Hospitals',
  'Colombo 05',
  'Colombo',
  5.2,
  16,
  4.8,
  285,
  4000,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Today · 15:00',
  'NJ',
  'MBBS (Col), MD (Col), MRCP (UK), MRCP (Edin), SCE MRCP Acute Medicine (UK) — Physician'
),
(
  'd34-sd',
  'Dr. Sajeevani Dissanayake',
  'Rheumatology',
  'Medihelp Hospitals',
  'Horana',
  'Horana',
  40,
  14,
  4.7,
  198,
  3500,
  '["English","Sinhala"]'::jsonb,
  false,
  5,
  'Tomorrow · 16:30',
  'SD',
  'MBBS, MD (Col), MRCP (UK) — Consultant Rheumatologist'
),
(
  'd35-ka',
  'Dr. K. D. Sewwandi Thejani Abeywardena',
  'Virology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  15,
  4.9,
  120,
  4500,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Wed · 10:00',
  'KA',
  'MBBS (Col), PgDip Medical Microbiology, MD Virology (Col) — Consultant Virologist'
),
(
  'd36-ma',
  'Dr. W. D. Malaka Amarasinghe',
  'Vascular & Transplant Surgery',
  'Lanka Hospitals',
  'Colombo 05',
  'Colombo',
  5.2,
  18,
  4.8,
  275,
  6000,
  '["English","Sinhala"]'::jsonb,
  false,
  6,
  'Tomorrow · 11:30',
  'MA',
  'Consultant Vascular & Transplant Surgeon'
),
(
  'd37-nf',
  'Prof. Nilesh Fernandopulle',
  'Gastroenterology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  25,
  4.9,
  650,
  6500,
  '["English","Sinhala"]'::jsonb,
  true,
  7,
  'Thu · 14:00',
  'NF',
  'Professor in Medicine and Consultant Medical Gastroenterologist'
),
(
  'd38-ss',
  'Dr. Solith Senanayake',
  'Cardiology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  16,
  4.8,
  240,
  5000,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Today · 17:00',
  'SS',
  'Consultant Cardiologist'
),
(
  'd39-sr',
  'Dr. Sanjeewa Rajapakse',
  'Cardiology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  19,
  4.8,
  310,
  5500,
  '["English","Sinhala"]'::jsonb,
  false,
  4,
  'Tomorrow · 09:00',
  'SR',
  'Consultant Cardiologist'
),
(
  'd40-ng',
  'Dr. Nalin D. Gunaratne',
  'Endocrinology',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  20,
  4.8,
  210,
  4500,
  '["English","Sinhala"]'::jsonb,
  true,
  3,
  'Tomorrow · 10:00',
  'NG',
  'Endocrinology Specialist'
),
(
  'd41-aa',
  'Dr. A.M.H.S. Attanayake',
  'Orthopaedic Surgery',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  18,
  4.7,
  350,
  5000,
  '["English","Sinhala"]'::jsonb,
  false,
  5,
  'Wed · 14:00',
  'AA',
  'Consultant Orthopaedic Surgeon'
),
(
  'd42-hh',
  'Dr. H.M.A. Herath',
  'Psychiatry & Mental Health',
  'Nawaloka Hospital',
  'Colombo 02',
  'Colombo',
  4.1,
  22,
  4.9,
  420,
  4500,
  '["English","Sinhala"]'::jsonb,
  true,
  2,
  'Today · 16:30',
  'HH',
  'Consultant Psychiatrist'
)
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name,
  specialty = EXCLUDED.specialty,
  hospital = EXCLUDED.hospital,
  branch = EXCLUDED.branch,
  city = EXCLUDED.city,
  "distanceKm" = EXCLUDED."distanceKm",
  "experienceYears" = EXCLUDED."experienceYears",
  rating = EXCLUDED.rating,
  reviews = EXCLUDED.reviews,
  fee = EXCLUDED.fee,
  languages = EXCLUDED.languages,
  online = EXCLUDED.online,
  queue = EXCLUDED.queue,
  "nextSlot" = EXCLUDED."nextSlot",
  "photoInitials" = EXCLUDED."photoInitials",
  about = EXCLUDED.about;
