/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as HospitalBranchesRouteImport } from './routes/hospital.branches'
import { Route as HospitalDoctorsRouteImport } from './routes/hospital.doctors'
import { Route as HospitalProfileRouteImport } from './routes/hospital.profile'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientAssistantRouteImport } from './routes/patient.assistant'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientElabRouteImport } from './routes/patient.elab'
import { Route as PatientEpassRouteImport } from './routes/patient.epass'
import { Route as PatientImagesRouteImport } from './routes/patient.images'
import { Route as PatientMedifitRouteImport } from './routes/patient.medifit'
import { Route as PatientMedmindEcareRouteImport } from './routes/patient.medmind-ecare'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientTelemedicineRouteImport } from './routes/patient.telemedicine'
import { Route as PatientTimelineRouteImport } from './routes/patient.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalBranchesRoute = HospitalBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalDoctorsRoute = HospitalDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalProfileRoute = HospitalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HospitalRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRoute,
} as any)
const PatientElabRoute = PatientElabRouteImport.update({
  id: '/elab',
  path: '/elab',
  getParentRoute: () => PatientRoute,
} as any)
const PatientEpassRoute = PatientEpassRouteImport.update({
  id: '/epass',
  path: '/epass',
  getParentRoute: () => PatientRoute,
} as any)
const PatientImagesRoute = PatientImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedifitRoute = PatientMedifitRouteImport.update({
  id: '/medifit',
  path: '/medifit',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedmindEcareRoute = PatientMedmindEcareRouteImport.update({
  id: '/medmind-ecare',
  path: '/medmind-ecare',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientTelemedicineRoute = PatientTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => PatientRoute,
} as any)
const PatientTimelineRoute = PatientTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/hospital/branches': typeof HospitalBranchesRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/elab': typeof PatientElabRoute
  '/patient/epass': typeof PatientEpassRoute
  '/patient/images': typeof PatientImagesRoute
  '/patient/medifit': typeof PatientMedifitRoute
  '/patient/medmind-ecare': typeof PatientMedmindEcareRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/telemedicine': typeof PatientTelemedicineRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/profile': typeof ApiProfileRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/hospital/branches': typeof HospitalBranchesRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/elab': typeof PatientElabRoute
  '/patient/epass': typeof PatientEpassRoute
  '/patient/images': typeof PatientImagesRoute
  '/patient/medifit': typeof PatientMedifitRoute
  '/patient/medmind-ecare': typeof PatientMedmindEcareRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/telemedicine': typeof PatientTelemedicineRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/hospital/branches': typeof HospitalBranchesRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/elab': typeof PatientElabRoute
  '/patient/epass': typeof PatientEpassRoute
  '/patient/images': typeof PatientImagesRoute
  '/patient/medifit': typeof PatientMedifitRoute
  '/patient/medmind-ecare': typeof PatientMedmindEcareRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/telemedicine': typeof PatientTelemedicineRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/hospital'
    | '/patient'
    | '/api/profile'
    | '/doctor/profile'
    | '/hospital/branches'
    | '/hospital/doctors'
    | '/hospital/profile'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/book'
    | '/patient/elab'
    | '/patient/epass'
    | '/patient/images'
    | '/patient/medifit'
    | '/patient/medmind-ecare'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/telemedicine'
    | '/patient/timeline'
    | '/admin/'
    | '/doctor/'
    | '/hospital/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/profile'
    | '/doctor/profile'
    | '/hospital/branches'
    | '/hospital/doctors'
    | '/hospital/profile'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/book'
    | '/patient/elab'
    | '/patient/epass'
    | '/patient/images'
    | '/patient/medifit'
    | '/patient/medmind-ecare'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/telemedicine'
    | '/patient/timeline'
    | '/admin'
    | '/doctor'
    | '/hospital'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/hospital'
    | '/patient'
    | '/api/profile'
    | '/doctor/profile'
    | '/hospital/branches'
    | '/hospital/doctors'
    | '/hospital/profile'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/book'
    | '/patient/elab'
    | '/patient/epass'
    | '/patient/images'
    | '/patient/medifit'
    | '/patient/medmind-ecare'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/telemedicine'
    | '/patient/timeline'
    | '/admin/'
    | '/doctor/'
    | '/hospital/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  HospitalRoute: typeof HospitalRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  ApiProfileRoute: typeof ApiProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/branches': {
      id: '/hospital/branches'
      path: '/branches'
      fullPath: '/hospital/branches'
      preLoaderRoute: typeof HospitalBranchesRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/doctors': {
      id: '/hospital/doctors'
      path: '/doctors'
      fullPath: '/hospital/doctors'
      preLoaderRoute: typeof HospitalDoctorsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/profile': {
      id: '/hospital/profile'
      path: '/profile'
      fullPath: '/hospital/profile'
      preLoaderRoute: typeof HospitalProfileRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/elab': {
      id: '/patient/elab'
      path: '/elab'
      fullPath: '/patient/elab'
      preLoaderRoute: typeof PatientElabRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/epass': {
      id: '/patient/epass'
      path: '/epass'
      fullPath: '/patient/epass'
      preLoaderRoute: typeof PatientEpassRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/images': {
      id: '/patient/images'
      path: '/images'
      fullPath: '/patient/images'
      preLoaderRoute: typeof PatientImagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medifit': {
      id: '/patient/medifit'
      path: '/medifit'
      fullPath: '/patient/medifit'
      preLoaderRoute: typeof PatientMedifitRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medmind-ecare': {
      id: '/patient/medmind-ecare'
      path: '/medmind-ecare'
      fullPath: '/patient/medmind-ecare'
      preLoaderRoute: typeof PatientMedmindEcareRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/telemedicine': {
      id: '/patient/telemedicine'
      path: '/telemedicine'
      fullPath: '/patient/telemedicine'
      preLoaderRoute: typeof PatientTelemedicineRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/timeline': {
      id: '/patient/timeline'
      path: '/timeline'
      fullPath: '/patient/timeline'
      preLoaderRoute: typeof PatientTimelineRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface HospitalRouteChildren {
  HospitalBranchesRoute: typeof HospitalBranchesRoute
  HospitalDoctorsRoute: typeof HospitalDoctorsRoute
  HospitalProfileRoute: typeof HospitalProfileRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

const HospitalRouteChildren: HospitalRouteChildren = {
  HospitalBranchesRoute: HospitalBranchesRoute,
  HospitalDoctorsRoute: HospitalDoctorsRoute,
  HospitalProfileRoute: HospitalProfileRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}

const HospitalRouteWithChildren = HospitalRoute._addFileChildren(
  HospitalRouteChildren,
)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientElabRoute: typeof PatientElabRoute
  PatientEpassRoute: typeof PatientEpassRoute
  PatientImagesRoute: typeof PatientImagesRoute
  PatientMedifitRoute: typeof PatientMedifitRoute
  PatientMedmindEcareRoute: typeof PatientMedmindEcareRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientTelemedicineRoute: typeof PatientTelemedicineRoute
  PatientTimelineRoute: typeof PatientTimelineRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientAssistantRoute: PatientAssistantRoute,
  PatientBookRoute: PatientBookRoute,
  PatientElabRoute: PatientElabRoute,
  PatientEpassRoute: PatientEpassRoute,
  PatientImagesRoute: PatientImagesRoute,
  PatientMedifitRoute: PatientMedifitRoute,
  PatientMedmindEcareRoute: PatientMedmindEcareRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientTelemedicineRoute: PatientTelemedicineRoute,
  PatientTimelineRoute: PatientTimelineRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DoctorRoute: DoctorRouteWithChildren,
  HospitalRoute: HospitalRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  ApiProfileRoute: ApiProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
