/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAssistantRouteImport } from './routes/patient.assistant'
import { Route as PatientBookRouteImport } from './routes/patient.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/book': typeof PatientBookRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/patient'
    | '/patient/assistant'
    | '/patient/book'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/patient/assistant' | '/patient/book' | '/patient'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/patient'
    | '/patient/assistant'
    | '/patient/book'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface PatientRouteChildren {
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAssistantRoute: PatientAssistantRoute,
  PatientBookRoute: PatientBookRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
